project_name: local-ssl-exporter
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: .
    binary: local-ssl-exporter
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
nfpms:
  - id: local-ssl-exporter-nfpms
    package_name: local-ssl-exporter
    homepage: https://github.com/transnano/local-ssl-exporter
    maintainer: Transnano <transnano.jp@gmail.com>
    description: local-ssl-exporter is prometheus exporter for local ssl certification metrics.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
